### Import modules

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import folium
from folium import IFrame
import base64
from PIL import Image
from io import BytesIO

### Create hike dataframe

For this to work properly, all I need to start is coordinate data and a code to connect the hike and its photo. Other features will come later.

In [46]:
df = {'lat': [37.269,
              34.585, 
              46.722,
              40.630,
              45.229,
              40.606,
              34.436, 
              46.958,
              45.402, 
              45.271,
              37.624,
              45.379
             ],
      'lon': [-112.947,
              -78.242, 
              -121.662,
              -111.655,
              -117.274,
              -111.693,
              -119.827,
              -121.877,
              -121.776,
              -121.739,
              -112.16, 
              -121.7392
             ],
      'code': ['angels_landing', 'bald_cypress_swamp', 'bald_mountain', 'donut_falls',
               'ice_lake', 'lake_blanche', 'santa_barbara_beach', 'tatoosh_ridge', 
               'trillium_lake', 'tolmie_peak', 'queens_garden', 'yocum_ridge'],
      'name': ["Angel's Landing, Zion National Park, UT", 'Bald Cypress Swamp, Ivanhoe, NC', 
               'Bald Mountain, Mt. Hood, OR', 'Donut Falls, Salt Lake City, UT', 'Ice Lake, Joseph, OR', 
               'Lake Blanche, Salt Lake City, UT', 'Santa Barbara Beach, Goleta, CA', 
               'Tatoosh Ridge, Packwood, WA', 'Tolmie Peak, Mt. Rainier National Park, WA', 
               'Trillium Lake, Mt. Hood, OR', 'Queens Garden, Bryce Canyon National Park, UT', 
               'Yocum Ridge, Mt. Hood, OR'],
      'month': [5, 6, 7, 10, 7, 10, 11, 8, 2, 8, 5, 8],
      'year': [2022, 2022, 2022, 2021, 2021, 2022, 2021, 2022, 2022, 2022, 2022, 2022]
     }

data = pd.DataFrame(df)
data

,lat,lon,code,name,month,year
0,37.269,-112.9470,angels_landing,"Angel's Landing, Zion National Park, UT",5,2022
1,34.585,-78.2420,bald_cypress_swamp,"Bald Cypress Swamp, Ivanhoe, NC",6,2022
2,46.722,-121.6620,bald_mountain,"Bald Mountain, Mt. Hood, OR",7,2022
3,40.630,-111.6550,donut_falls,"Donut Falls, Salt Lake City, UT",10,2021
4,45.229,-117.2740,ice_lake,"Ice Lake, Joseph, OR",7,2021
5,40.606,-111.6930,lake_blanche,"Lake Blanche, Salt Lake City, UT",10,2022
6,34.436,-119.8270,santa_barbara_beach,"Santa Barbara Beach, Goleta, CA",11,2021
7,46.958,-121.8770,tatoosh_ridge,"Tatoosh Ridge, Packwood, WA",8,2022
8,45.402,-121.7760,trillium_lake,"Tolmie Peak, Mt. Rainier National Park, WA",2,2022
9,45.271,-121.7390,tolmie_peak,"Trillium Lake, Mt. Hood, OR",8,2022
10,37.624,-112.1600,queens_garden,"Queens Garden, Bryce Canyon National Park, UT",5,2022
11,45.379,-121.7392,yocum_ridge,"Yocum Ridge, Mt. Hood, OR",8,2022

### Initialize map

In [ ]:
world = folium.Map(zoom_start=4, location=[42, -115])
            
x = data[['lat', 'lon', 'code', 'name']].copy()

for index, row in x.iterrows():
    code = row['code']
    name = row['name']
    encoded = base64.b64encode(open(f'photos/{code}.png', 'rb').read())
    html = '<img src="data:image/png;base64,{}">'.format
    iframe = IFrame(html(encoded.decode('UTF-8')), width=500, height=400)
    popup = folium.Popup(iframe, max_width=500) 
    folium.Marker([row['lat'], row['lon']], tooltip=name, popup=popup, 
              icon=folium.Icon(color = 'gray')).add_to(world)               
              
world